# Generated by Django 4.1.1 on 2022-10-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0002_mahasiswafkip_rename_mahasiswa_dosenfkip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenfkip',
            name='foto',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswafkip',
            name='foto',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
