# Generated by Django 4.1.1 on 2022-10-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0003_alter_dosenfkip_foto_alter_mahasiswafkip_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('ttl', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=300)),
                ('foto', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
