# Generated by Django 4.1.1 on 2022-10-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0005_dosenfaperta_dosenfeb_dosenfh_dosenfisip_dosenfk_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffFaperta',
            new_name='StafFaperta',
        ),
    ]
