# Generated by Django 4.1.1 on 2022-10-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0006_rename_stafffaperta_staffaperta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StafFaperta',
            new_name='StaffFaperta',
        ),
    ]
