# Generated by Django 4.1.1 on 2022-10-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0007_rename_staffaperta_stafffaperta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswafkip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
