# Generated by Django 4.1 on 2022-10-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0014_hmjfkip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutaFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=300, null=True)),
                ('namaduta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatakuliahFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=300, null=True)),
                ('namamatakuliah', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RuanganFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=300, null=True)),
                ('namaruangan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UkmFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=300, null=True)),
                ('namaukm', models.CharField(max_length=100)),
            ],
        ),
    ]
