# Generated by Django 4.1 on 2022-10-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0015_dutafkip_matakuliahfkip_ruanganfkip_ukmfkip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkreditasiFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=50)),
            ],
        ),
    ]
